on: [push]
#  schedule:
#    - cron: '0 4 * * 1'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/data_science'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run convertion script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python ds/convert.py

      - name: Run model creation script
        run: python ds/creamodelos.py
      
      - name: Commit files
        run: |
          git config --local user.email "deiaproy@gmail.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add changes" && git push)