on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:


          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python ds/convert.py